version: '3.9'

services:
  pdf-grinder-api:
    build: .
    container_name: pdf-grinder-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - UPLOAD_DIR=uploads
      - MERGED_DIR=merged
    restart: unless-stopped