# 1. base image
FROM node:18

# 2. Create directory for the app
WORKDIR /app

# 3. Copy package.json & package-lock.json
COPY package*.json ./

# 4. Install dependencies
RUN npm install

# 5. Copy the rest of the application code
COPY . .

# 6. Create directories for uploads and merged
RUN mkdir -p uploads merged

# 7. Port to expose
EXPOSE 3000

# 8. Command to run the application
CMD ["npm", "run", "dev", "start"]
